security:
    encoders:
        App\Entity\Users:
            algorithm: bcrypt
    providers:
        users:
            entity:
                class: Entity:Users
                property: username
    firewalls:
        main:
            pattern: ^/userpanel
            http_basic: ~
            provider: users
    access_control:
        - { path: ^/userpanel, roles: ROLE_USER }
        - { path: ^/adminpanel, roles: ROLE_ADMIN }
        - { path: ^/resume, roles: ROLE_USER }
