security:
    encoders:
        App\Entity\Users:
            algorithm: bcrypt
    providers:
        users:
            entity:
                class: App\Entity\Users
                property: username
    firewalls:
        main:
            anonymous: ~
            form_login:
                provider: users
                login_path: login
                check_path: login_check
                post_only: true
            logout: true

    access_control:
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/userpanel, roles: ROLE_USER }
        - { path: ^/adminpanel, roles: ROLE_ADMIN }
        - { path: ^/resume, roles: ROLE_USER }
