security:
    encoders:
        App\Entity\Users:
            algorithm: bcrypt
        App\Entity\Visitors:
            algorithm: plaintext
    providers:
        users:
            entity:
                class: App\Entity\Users
                property: username
        visitors:
            entity:
                class: App\Entity\Visitors
                property: email
    firewalls:
        main:
            anonymous: ~
            form_login:
                provider: users
                login_path: login
                check_path: login_check
                post_only: true
            logout:
                path: /logout
                target: /
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/userpanel, roles: ROLE_USER }
        - { path: ^/resume, roles: ROLE_USER }
